name: Build and Release Pulse Panel

on:
  push:
    branches:
      - main  # Set this to the branch you want to build from

jobs:
  build:
    runs-on: windows-latest  # Specifies that the job should run on the latest Windows runner

    steps:
      - uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies with Bun
        run: bun install

      - name: Build Electron app with Bun
        run: |
          set env DEBUG=electron-builder
          bun run build -p never

      - name: Extract Version
        run: echo "APP_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-electron-app
          path: ./release/**/*

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          artifacts: ./release/${{ env.APP_VERSION }}/pulse-panel_${{ env.APP_VERSION }}.exe
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/${{ env.APP_VERSION }}/pulse-panel_${{ env.APP_VERSION }}.exe
          asset_name: pulse-panel_${{ env.APP_VERSION }}.exe
          asset_content_type: application/octet-stream
